from __future__ import annotations

import json
import hashlib
import sqlite3
from pathlib import Path
from typing import Iterable, Any

from .text_normalize import token_key
from .translation_models import TranslationRecord


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS translations (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    normalized_source TEXT NOT NULL,
    vi TEXT NOT NULL,
    speaker TEXT,
    area TEXT,
    content_type TEXT NOT NULL,
    status TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_translations_normalized
    ON translations(normalized_source);
CREATE INDEX IF NOT EXISTS idx_translations_context
    ON translations(content_type, speaker, area, status);

CREATE TABLE IF NOT EXISTS aliases (
    translation_id TEXT NOT NULL,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    FOREIGN KEY(translation_id) REFERENCES translations(id)
);
CREATE INDEX IF NOT EXISTS idx_aliases_normalized
    ON aliases(normalized_alias);
"""


def load_source_corpus(path: Path) -> dict[str, dict[str, Any]]:
    """Load gitignored English source corpus generated by source_sync.py."""
    records: dict[str, dict[str, Any]] = {}
    if not path.exists():
        return records

    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            source_id = str(item["source_id"])
            if source_id in records:
                raise ValueError(f"Duplicate source_id {source_id} at line {line_no}")
            records[source_id] = item
    return records


def load_vi_entries(path: Path) -> list[dict[str, Any]]:
    """Load our committed Vietnamese translations without raw English source."""
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError(f"{path} must contain a JSON array")
    if any(not isinstance(item, dict) for item in payload):
        raise ValueError(f"{path} contains a non-object translation entry")
    return payload


def compile_translation_records(
    corpus_path: Path,
    vi_path: Path,
) -> tuple[list[TranslationRecord], dict[str, int]]:
    corpus = load_source_corpus(corpus_path)
    vi_entries = load_vi_entries(vi_path)

    records: list[TranslationRecord] = []
    missing_source = 0
    skipped_empty = 0
    seen: set[str] = set()

    for item in vi_entries:
        source_id = str(item.get("source_id") or "").strip()
        vi_raw = str(item.get("vi") or "")
        vi = vi_raw.strip()
        status = str(item.get("status") or "draft")

        if status not in {"draft", "reviewed", "approved"}:
            raise ValueError(f"Invalid translation status for {source_id}: {status}")
        if source_id in seen:
            raise ValueError(f"Duplicate Vietnamese source_id: {source_id}")
        if source_id:
            seen.add(source_id)

        if not source_id or not vi:
            skipped_empty += 1
            continue

        source = corpus.get(source_id)
        if source is None:
            missing_source += 1
            continue

        if "source_sha256" in item:
            expected = hashlib.sha256(str(source["source"]).encode("utf-8")).hexdigest()
            if item["source_sha256"] != expected:
                raise ValueError(f"Source changed since translation review: {source_id}")
        if "vi_sha256" in item:
            expected = hashlib.sha256(vi_raw.encode("utf-8")).hexdigest()
            if item["vi_sha256"] != expected:
                raise ValueError(f"Vietnamese text changed since review: {source_id}")

        records.append(
            TranslationRecord(
                id=source_id,
                source=str(source["source"]),
                vi=vi,
                speaker=source.get("speaker"),
                area=source.get("area"),
                content_type="dialogue",
                status=status,
                aliases=tuple(str(x) for x in item.get("aliases", [])),
            )
        )

    stats = {
        "corpus_records": len(corpus),
        "vi_entries": len(vi_entries),
        "compiled_records": len(records),
        "missing_source": missing_source,
        "skipped_empty": skipped_empty,
    }
    return records, stats


def build_sqlite(records: Iterable[TranslationRecord], db_path: Path) -> None:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(SCHEMA_SQL)

        for record in records:
            normalized = token_key(record.source)
            if not normalized:
                raise ValueError(f"Record {record.id} has an empty normalized source")

            conn.execute(
                """
                INSERT INTO translations
                    (id, source, normalized_source, vi, speaker, area, content_type, status)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    record.id,
                    record.source,
                    normalized,
                    record.vi,
                    record.speaker,
                    record.area,
                    record.content_type,
                    record.status,
                ),
            )

            for alias in record.aliases:
                normalized_alias = token_key(alias)
                if normalized_alias:
                    conn.execute(
                        """
                        INSERT INTO aliases
                            (translation_id, alias, normalized_alias)
                        VALUES (?, ?, ?)
                        """,
                        (record.id, alias, normalized_alias),
                    )

        conn.commit()
    finally:
        conn.close()


class TranslationStore:
    def __init__(self, db_path: Path) -> None:
        self.db_path = db_path
        self._conn = sqlite3.connect(db_path)
        self._conn.row_factory = sqlite3.Row

    def close(self) -> None:
        self._conn.close()

    def all_records(
        self,
        *,
        content_type: str = "dialogue",
        statuses: tuple[str, ...] = ("reviewed", "approved"),
    ) -> list[TranslationRecord]:
        placeholders = ",".join("?" for _ in statuses)
        rows = self._conn.execute(
            f"""
            SELECT * FROM translations
            WHERE content_type = ?
              AND status IN ({placeholders})
            """,
            (content_type, *statuses),
        ).fetchall()

        return [self._record_from_row(row) for row in rows]

    def exact(
        self,
        normalized_text: str,
        *,
        speaker: str | None = None,
        area: str | None = None,
        content_type: str = "dialogue",
        statuses: tuple[str, ...] = ("reviewed", "approved"),
    ) -> TranslationRecord | None:
        placeholders = ",".join("?" for _ in statuses)
        params: list[object] = [normalized_text, content_type, *statuses]

        query = f"""
            SELECT t.*
            FROM translations t
            WHERE t.normalized_source = ?
              AND t.content_type = ?
              AND t.status IN ({placeholders})
        """

        if speaker:
            query += " AND (t.speaker IS NULL OR lower(t.speaker) = lower(?))"
            params.append(speaker)
        if area:
            query += " AND (t.area IS NULL OR lower(t.area) = lower(?))"
            params.append(area)

        query += " ORDER BY CASE t.status WHEN 'approved' THEN 0 ELSE 1 END LIMIT 1"
        row = self._conn.execute(query, params).fetchone()
        if row:
            return self._record_from_row(row)

        alias_params: list[object] = [normalized_text, content_type, *statuses]
        alias_query = f"""
            SELECT t.*
            FROM aliases a
            JOIN translations t ON t.id = a.translation_id
            WHERE a.normalized_alias = ?
              AND t.content_type = ?
              AND t.status IN ({placeholders})
        """
        if speaker:
            alias_query += " AND (t.speaker IS NULL OR lower(t.speaker) = lower(?))"
            alias_params.append(speaker)
        if area:
            alias_query += " AND (t.area IS NULL OR lower(t.area) = lower(?))"
            alias_params.append(area)
        alias_query += " ORDER BY CASE t.status WHEN 'approved' THEN 0 ELSE 1 END LIMIT 1"

        row = self._conn.execute(alias_query, alias_params).fetchone()
        return self._record_from_row(row) if row else None

    def aliases_for(self, record_id: str) -> tuple[str, ...]:
        rows = self._conn.execute(
            "SELECT alias FROM aliases WHERE translation_id = ?",
            (record_id,),
        ).fetchall()
        return tuple(row["alias"] for row in rows)

    def _record_from_row(self, row: sqlite3.Row) -> TranslationRecord:
        return TranslationRecord(
            id=row["id"],
            source=row["source"],
            vi=row["vi"],
            speaker=row["speaker"],
            area=row["area"],
            content_type=row["content_type"],
            status=row["status"],
            aliases=self.aliases_for(row["id"]),
        )
